import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./utils/provider";
import Navbar from "src/components/organisms/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Webshop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Provider>
					<Navbar />
					<div className="container mx-auto py-12 max-w-6xl">
						{children}
					</div>
				</Provider>
			</body>
		</html>
	);
}
